//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BildingTime.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string ProductArticleNumber { get; set; }
        public int ProductNameID { get; set; }
        public string ProductDescription { get; set; }
        public int ProductCategoryId { get; set; }
        public byte[] ProductPhoto { get; set; }
        public int ProductProviderId { get; set; }
        public int ProductManufacturerId { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ProductСategory ProductСategory { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ProductName ProductName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
